from enum import Enum


class PaymentStatusReason(str, Enum):
    APPROVED = "APPROVED"
    BUDGET_CATEGORY_RESTRICTION = "BUDGET_CATEGORY_RESTRICTION"
    BUDGET_EXPIRED = "BUDGET_EXPIRED"
    BUDGET_MERCHANT_RESTRICTION = "BUDGET_MERCHANT_RESTRICTION"
    BUDGET_NOT_YET_STARTED = "BUDGET_NOT_YET_STARTED"
    CARD_EXPIRED = "CARD_EXPIRED"
    CARD_NOT_ACTIVE = "CARD_NOT_ACTIVE"
    CARD_SUSPENDED = "CARD_SUSPENDED"
    CARD_TERMINATED = "CARD_TERMINATED"
    COMPLIANCE_BLOCKED = "COMPLIANCE_BLOCKED"
    EXCEEDED_ANCESTOR_BUDGET_LIMIT = "EXCEEDED_ANCESTOR_BUDGET_LIMIT"
    EXCEEDED_BUDGET_LIMIT = "EXCEEDED_BUDGET_LIMIT"
    EXCEEDED_BUDGET_TRANSACTION_LIMIT = "EXCEEDED_BUDGET_TRANSACTION_LIMIT"
    EXCEEDED_CARD_LIMIT = "EXCEEDED_CARD_LIMIT"
    EXCEEDED_GLOBAL_LIMIT = "EXCEEDED_GLOBAL_LIMIT"
    EXCEEDED_PIN_ATTEMPTS = "EXCEEDED_PIN_ATTEMPTS"
    EXCEEDED_USER_LIMIT = "EXCEEDED_USER_LIMIT"
    INSIDE_SANCTIONED_COUNTRY = "INSIDE_SANCTIONED_COUNTRY"
    INVALID_BILLING_ADDRESS = "INVALID_BILLING_ADDRESS"
    INVALID_CARD_CREDENTIALS = "INVALID_CARD_CREDENTIALS"
    INVALID_CVV = "INVALID_CVV"
    INVALID_EXPIRATION_DATE = "INVALID_EXPIRATION_DATE"
    INVALID_PIN = "INVALID_PIN"
    MCC_BLOCKED = "MCC_BLOCKED"
    NO_BUDGET = "NO_BUDGET"
    OTHER = "OTHER"
    SOFT_EXPIRATION = "SOFT_EXPIRATION"
    SUSPECTED_FRAUD = "SUSPECTED_FRAUD"
    TOS_BLOCKED = "TOS_BLOCKED"
    TRANSFERRED_CARD_NEW_MERCHANT = "TRANSFERRED_CARD_NEW_MERCHANT"
    USER_SUSPENDED = "USER_SUSPENDED"

    def __str__(self) -> str:
        return str(self.value)
