from enum import Enum


class CashTransactionType(str, Enum):
    ADJUSTMENT = "ADJUSTMENT"
    BOOK_TRANSFER = "BOOK_TRANSFER"
    BREX_OPERATIONAL_TRANSFER = "BREX_OPERATIONAL_TRANSFER"
    CARD_COLLECTION = "CARD_COLLECTION"
    CRYPTO_BRIDGE = "CRYPTO_BRIDGE"
    DIVIDEND = "DIVIDEND"
    FBO_TRANSFER = "FBO_TRANSFER"
    FEE = "FEE"
    INTEREST = "INTEREST"
    INTRA_CUSTOMER_ACCOUNT_BOOK_TRANSFER = "INTRA_CUSTOMER_ACCOUNT_BOOK_TRANSFER"
    PAYMENT = "PAYMENT"
    RECEIVABLES_OFFERS_ADVANCE = "RECEIVABLES_OFFERS_ADVANCE"
    RECEIVABLES_OFFERS_COLLECTION = "RECEIVABLES_OFFERS_COLLECTION"
    RECEIVABLES_OFFERS_REPAYMENT = "RECEIVABLES_OFFERS_REPAYMENT"
    REWARDS_REDEMPTION = "REWARDS_REDEMPTION"

    def __str__(self) -> str:
        return str(self.value)
